blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('blog/', views.PostListView.as_view(), name='post-list'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<slug:slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='post-category'),
    path('post-create/', views.PostCreateView.as_view(), name='post-create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('contact/', ContactView.as_view(), name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from tinymce.models import HTMLField

class Author(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.slug




class Post(models.Model):
    title = models.CharField(max_length=140)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    content = HTMLField('Content')
    timestamp = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    comment_count = models.IntegerField(default=0)
    featured = models.BooleanField()
    prev_post = models.ForeignKey(
        'self', related_name='previous_post', on_delete=models.SET_NULL, null=True, blank=True)
    nxt_post = models.ForeignKey(
        'self', related_name='next_post', on_delete=models.SET_NULL, null=True, blank=True)


    class Meta:
        ordering = ['-timestamp', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})
        
    def get_update_url(self):
        return reverse('blog:post-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:post-delete', kwargs={'slug': self.slug})


    @property
    def get_comments(self):
        return self.comment_set.all()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.body[:30]


class Gallery(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='gallery')

    class Meta:
        verbose_name_plural = 'Gallery'

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.mail import send_mail


from .models import Post

class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Your Name',
            })
        )
    message = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': "Your Message (Not less than 2 words)",
            'rows': '4',
        }
    ))

    def clean_message(self):
        message = self.cleaned_data.get('message', '')
        num_words = len(message.split())
        if num_words < 2:
            raise forms.ValidationError("Not enough words!")
        return message

    def send_mail(self):
        message = f"From: {self.cleaned_data['name']}\n\nMessage:\n\
            {self.cleaned_data['message']}"

        send_mail(
            subject='Mail from the site',
            message=message,
            from_email='contact@domain.com',
            recipient_list=
            ['customerservices@domain.com',],
            fail_silently=False,
        )


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ('comment_count', 'author', )

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from marketing.models import Subscriber
from django.contrib.messages.views import SuccessMessageMixin



from .models import Author, Category, Comment, Gallery, Post
from .forms import ContactForm


class ContactView(SuccessMessageMixin, FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = '/'
    success_message = ('Your message has sent successful. '
                       'We will get to you shortly.')

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)



def get_category_count():
    categories = Category.objects.all().annotate(posts_count=Count('post'))
    return categories


class SearchResultsView(ListView):
    model = Post
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q' or None)
        if query:
            object_list = Post.objects.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query)
            )
            return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        return context


class HomePageView(ListView):
    queryset = Post.objects.all()[:3]
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['featured_posts'] = Post.objects.filter(featured=True)[:4]
        context['gallery_items'] = Gallery.objects.all()[:4]
        return context

    def post(self, request):
        if request.method == 'POST':
            email = request.POST['email']
            subscriber, created = Subscriber.objects.get_or_create(email=email)

            if created:
                messages.success(request, 'Please check your e-mail for confirmation')
            elif subscriber:
                 messages.success(request, 'This email already in the list')
        return super().get(request)


class PostListView(ListView):
    model = Post
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        return context


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        context['comments'] = self.object.get_comments
        context['latest_posts'] = Post.objects.all()[:3]
        return context

    def post(self, request, **kwargs):
        if request.method == 'POST':
            post = Post.objects.get(slug=kwargs['slug'])
            author = request.user.username
            body = request.POST['usercomment']
            Comment.objects.create(post=post, author=author, body=body)
        return redirect('blog:post-detail', slug=kwargs['slug'])


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'overview', 'content', 'categories', 'thumbnail', 'featured']

    def form_valid(self, form):
        author = get_object_or_404(Author, user=self.request.user)
        form.instance.author = author
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'overview', 'content', 'categories', 'thumbnail', 'featured',]

    def form_valid(self, form):
        author = get_object_or_404(Author, user=self.request.user)
        form.instance.author = author
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author.user:
            return True
        return False

    # def form_valid(self, form):
    #     form.instance.author = self.request.user.id
    #     action = self.request.POST.get('action')
    #     if action == 'SAVE':
    #         return super().form_valid(form)
    #     elif action == 'PREVIEW':
    #         preview = Post(
    #             title = form.cleaned_data['title'],
    #             slug = form.cleaned_data['slug'],
    #             author = form.cleaned_data['user'],
    #         )
    #         context = self.get_context_data(preview=preview)
    #         return self.render_to_response(context=context)
    #     return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post-list')

    def test_func(self):
        post = self.get_object()
        if post.author.user == self.request.user:
            return True
        return False


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'blog/post_category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        context['latest_posts'] = Post.objects.all()[:3]
        return context

blog/templates/blog/contact.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container my-5">
    <div class="row col-md-6 offset-3">
        <form action="" class="">
            {% csrf_token %}
            {{ form | crispy}}
            <button type="submit" class="btn btn-primary mt-3 rounded">Send Message</button>
        </form>
    </div>
</div>

<!-- 
            <div class="col-md-4 text-md-right text-center">
                <img class='contact-image p-1 rounded' src="{% static 'img/about-image.png' %} " alt="Innocent Zenda">
                <div>
                    <h5 class="mt-3">Innocent Zenda</h5>
                    <h4>Web Developer</h4>
                </div>
            </div> -->
       

{% endblock content %}

blog/templates/blog/post_category.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in category.post_set.all %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="post.html"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      <!-- <div class="date meta-last">{{ post.timestamp |date}}</div> -->
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div>
                    <a href="{{ post.get_absolute_url }}">
                      <h3 class="h4">{{ post.title }}</h3>
                    </a>
                    <p class="lead">
                      {{ post.overview }}
                    </p>
                    <p>
                      {{ post.content | safe }}
                    </p>
                    <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                        <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                        <div class="title"><span>{{ post.author }}</span></div></a>
                      <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                      <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                    </footer>
                  </div>
                </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                     <i class="fa fa-angle-left"></i>
                    </a>
                  </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                  <li class="page-item">
                    <a href="?page={{ num }}" class="page-link active">{{ num }}</a>
                  </li>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                      <li class="page-item">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                      </li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </main>
        {% include 'aside.html' with object_list=latest_posts %}
      </div>
    </div>
{% endblock content %}
        
    
    
    

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container my-5">
        <h2>Are you sure to delete {{ object.title }}?</h2>
        <form method='POST'>
            {% csrf_token %}
            <div class="mt-5">
                <button type='submit' class="btn btn-danger">Delete</button>
                <a class="btn btn-secondary ml-2" href='{{ object.get_absolute_url }}'>
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock content %}
    
    

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail">
                <img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid">
              </div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category">
                  {% for cat in post.categories.all %}
                  <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                  {% endfor %}
                  </div>
                </div>
                <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                  
                  {% if request.user.is_authenticated %}
                    
                    {% if post.author.user == request.user %}
                    <div class='my-3 text-center d-inline'>
                        <a class="btn btn-primary mr-2" href="{{ post.get_update_url }}">
                          Update
                        </a>
                        <a class="btn btn-danger" href="{{ post.get_delete_url }}">
                          Delete
                        </a>
                      </div>
                    {% endif %}
                      
                    
                  {% endif %}
                    
                  
                  <!-- <div class='my-3 text-center d-inline'>
                      <a class="btn btn-primary mr-2" href="{{ post.get_update_url }}">
                        Update
                      </a>
                      <a class="btn btn-danger" href="{{ post.get_delete_url }}">
                        Delete
                      </a>
                    </div> -->

                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar">
                      <img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid">
                    </div>
                    <div class="title"><span>{{ post.author }}</span></div></a>
                  <div class="d-flex align-items-center flex-wrap">       
                    <div class="date">
                      <i class="icon-clock"></i>{{ post.timestamp |timesince}} ago
                    </div>
                    <div class="views"><i class="icon-eye"></i> 500</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ comment_count }}</div>
                  </div>
                </div>
                
                <div class="post-body">
                  <p class="lead">
                    {{ post.overview }}
                  </p>
                  <p>
                    {{ post.content | safe }}
                  </p>
                </div>
                
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                {% if post.prev_post %}
                <a href="{{ post.prev_post.get_absolute_url }}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev">
                      <i class="fa fa-angle-left"></i>
                    </div>
                    <div class="text">
                      <strong class="text-primary">Previous Post </strong>
                      <h6>{{ post.prev_post.title }}</h6>
                    </div>
                  </a>
                {% endif %}
                
                {% if post.nxt_post %}
                <a href="{{ post.nxt_post.get_absolute_url }}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text">
                      <strong class="text-primary">Next Post </strong>
                      <h6>{{ post.nxt_post.title }}</h6>
                    </div>
                    <div class="icon next">
                      <i class="fa fa-angle-right">   </i>
                    </div>
                  </a>
                {% endif %}
                  
                </div>
                    
                {% if comments %}      
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">({{ post.comment_set.count }})</span></h3>
                  </header>
                  {% for comment in comments %}
                  <div class="comment">
                      <div class="comment-header d-flex justify-content-between">
                        <div class="user d-flex align-items-center">
                            <!-- <div class="image">
                              <img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid rounded-circle">
                            </div> -->
                            <div class="image">
                              <img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle">
                            </div>
                          
                          <div class="title"><strong>{{ comment.author }}</strong><span class="date">{{ comment.timestamp|date }}</span></div>
                        </div>
                      </div>
                      <div class="comment-body">
                        <p>
                          {{ comment.body }}
                        </p>
                      </div>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}

                {% if request.user.is_authenticated %}
                <div class="add-comment">
                    <header>
                      <h3 class="h6">Leave a reply</h3>
                    </header>
                    <form action="." class="commenting-form" method="POST">
                      {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12">
                          <textarea name="usercomment" id="usercomment" placeholder="Type your comment" class="form-control"></textarea>
                        </div>
                        <div class="form-group col-md-12">
                          <button type="submit" class="btn btn-secondary">Submit Comment</button>
                        </div>
                      </div>
                    </form>
                  </div>
                {% else %}
                  <hr>
                  <a href="{% url 'login' %}" class="btn btn-link">Login to comment</a>  
                {% endif %}

              </div>
            </div>
          </div>
        </main>

        {% include 'aside.html' with object_list=latest_posts %}
      </div>
    </div>

{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}


{% comment %}
{% load markdownify %}
{% endcomment %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container my-5">

    {% if preview %}
    {{ preview.title | markdownify }}
    {% endif %}

    <form class="col-lg-8 offset-2" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary" name='action' value='SAVE'>Create</button>
        <button type="submit" class="btn btn-primary" name='action' value='PREVIEW'>Preview</button>
    </form>
</div>


<script src="{% static 'js/slugify.js' %}"></script>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in object_list %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="post.html"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      <!-- <div class="date meta-last">{{ post.timestamp |date}}</div> -->
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div>
                    <div>
                      <a href="{{ post.get_absolute_url }}">
                        <h3 class="h4">{{ post.title }}</h3>
                      </a>
                      <p class="text-muted">
                        {{ post.overview }}
                      </p>
                    </div>
                    <footer class="post-footer d-flex align-items-center">
                      <a href="#" class="author d-flex align-items-center flex-wrap">
                        <div class="avatar">
                          <img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid">
                        </div>
                        <div class="title">
                          <span>{{ post.author }}</span>
                        </div>
                      </a>
                      <div class="date">
                        <i class="icon-clock"></i>
                        {{ post.timestamp|timesince }} ago
                      </div>
                      <div class="comments meta-last">
                        <i class="icon-comment"></i>{{ post.comment_count }}
                      </div>
                    </footer>
                  </div>
                </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                     <i class="fa fa-angle-left"></i>
                    </a>
                  </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                  <li class="page-item">
                    <a href="?page={{ num }}" class="page-link active">{{ num }}</a>
                  </li>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                      <li class="page-item">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                      </li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </main>
        {% include 'aside.html' %}
      </div>
    </div>
{% endblock content %}
        
    
    