blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('blog/', views.PostListView.as_view(), name='post-list'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<slug:slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='post-category'),
    path('post-create/', views.PostCreateView.as_view(), name='post-create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('contact/', ContactView.as_view(), name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserRegisterView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from tinymce.models import HTMLField

class Author(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.slug




class Post(models.Model):
    title = models.CharField(max_length=140)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    content = HTMLField('Content')
    timestamp = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    comment_count = models.IntegerField(default=0)
    featured = models.BooleanField()
    prev_post = models.ForeignKey(
        'self', related_name='previous_post', on_delete=models.SET_NULL, null=True, blank=True)
    nxt_post = models.ForeignKey(
        'self', related_name='next_post', on_delete=models.SET_NULL, null=True, blank=True)


    class Meta:
        ordering = ['-timestamp', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})
        
    def get_update_url(self):
        return reverse('blog:post-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:post-delete', kwargs={'slug': self.slug})


    @property
    def get_comments(self):
        return self.comment_set.all()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.body[:30]


class Gallery(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='gallery')

    class Meta:
        verbose_name_plural = 'Gallery'

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.mail import send_mail


from .models import Post

class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Your Name',
            })
        )
    message = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': "Your Message (Not less than 2 words)",
            'rows': '4',
        }
    ))

    def clean_message(self):
        message = self.cleaned_data.get('message', '')
        num_words = len(message.split())
        if num_words < 2:
            raise forms.ValidationError("Not enough words!")
        return message

    def send_mail(self):
        message = f"From: {self.cleaned_data['name']}\n\nMessage:\n\
            {self.cleaned_data['message']}"

        send_mail(
            subject='Mail from the site',
            message=message,
            from_email='contact@domain.com',
            recipient_list=
            ['customerservices@domain.com',],
            fail_silently=False,
        )


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ('comment_count', 'author', )

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from marketing.models import Subscriber
from django.contrib.messages.views import SuccessMessageMixin



from .models import Author, Category, Comment, Gallery, Post
from .forms import ContactForm


class ContactView(SuccessMessageMixin, FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = '/'
    success_message = ('Your message has sent successful. '
                       'We will get to you shortly.')

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)



def get_category_count():
    categories = Category.objects.all().annotate(posts_count=Count('post'))
    return categories


class SearchResultsView(ListView):
    model = Post
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q' or None)
        if query:
            object_list = Post.objects.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query)
            )
            return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        return context


class HomePageView(ListView):
    queryset = Post.objects.all()[:3]
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['featured_posts'] = Post.objects.filter(featured=True)[:4]
        context['gallery_items'] = Gallery.objects.all()[:4]
        return context

    def post(self, request):
        if request.method == 'POST':
            email = request.POST['email']
            subscriber, created = Subscriber.objects.get_or_create(email=email)

            if created:
                messages.success(request, 'Please check your e-mail for confirmation')
            elif subscriber:
                 messages.success(request, 'This email already in the list')
        return super().get(request)


class PostListView(ListView):
    model = Post
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        return context


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        context['comments'] = self.object.get_comments
        context['latest_posts'] = Post.objects.all()[:3]
        return context

    def post(self, request, **kwargs):
        if request.method == 'POST':
            post = Post.objects.get(slug=kwargs['slug'])
            author = request.user.username
            body = request.POST['usercomment']
            Comment.objects.create(post=post, author=author, body=body)
        return redirect('blog:post-detail', slug=kwargs['slug'])


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'overview', 'content', 'categories', 'thumbnail', 'featured']

    def form_valid(self, form):
        author = get_object_or_404(Author, user=self.request.user)
        form.instance.author = author
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'overview', 'content', 'categories', 'thumbnail', 'featured',]

    def form_valid(self, form):
        author = get_object_or_404(Author, user=self.request.user)
        form.instance.author = author
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author.user:
            return True
        return False

    # def form_valid(self, form):
    #     form.instance.author = self.request.user.id
    #     action = self.request.POST.get('action')
    #     if action == 'SAVE':
    #         return super().form_valid(form)
    #     elif action == 'PREVIEW':
    #         preview = Post(
    #             title = form.cleaned_data['title'],
    #             slug = form.cleaned_data['slug'],
    #             author = form.cleaned_data['user'],
    #         )
    #         context = self.get_context_data(preview=preview)
    #         return self.render_to_response(context=context)
    #     return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post-list')

    def test_func(self):
        post = self.get_object()
        if post.author.user == self.request.user:
            return True
        return False


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'blog/post_category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_count'] = get_category_count()
        context['latest_posts'] = Post.objects.all()[:3]
        return context

templates/aside.html
{% load static %}

<aside class="col-lg-4">
        <!-- Widget [Search Bar Widget]-->
        <div class="widget search">
          <header>
            <h3 class="h6">Search the blog</h3>
          </header>
          <form action="{% url 'blog:search-results' %}" class="search-form" method="GET">
            
            <div class="form-group">
              <input type="text" name='q' placeholder="What are you looking for?">
              <button type="submit" class="submit"><i class="icon-search"></i></button>
            </div>
          </form>
        </div>
        <!-- Widget [Latest Posts Widget]        -->
        <div class="widget latest-posts">
          <header>
            <h3 class="h6">Latest Posts</h3>
          </header>
          <div class="blog-posts">
          {% for post in object_list %}
          <a href="{{ post.get_absolute_url }}">
              <div class="item d-flex align-items-center">
                <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                <div class="title"><strong>{{ post.title }}</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i> 500</div>
                    <div class="comments">
                      <i class="icon-comment"></i> {{ post.comment_set.all.count }}
                    </div>
                  </div>
                </div>
              </div>
            </a>
          {% endfor %}
          </div>
        </div>
        <!-- Widget [Categories Widget]-->
        <div class="widget categories">
          <header>
            <h3 class="h6">Categories</h3>
          </header>
          {% for cat in category_count %}
          <div class="item d-flex justify-content-between">
            <a href="{% url 'blog:post-category' cat.slug %}">{{ cat.name }}</a><span>{{ cat.posts_count}}</span>
          </div>
          {% endfor %}
        </div>
      </aside>

templates/base.html
<!DOCTYPE html>
<html>

    {% include 'head.html' %}
    
    <body>  
        {% include 'header.html' %}

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} text-center">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}
        
        {% include 'footer.html' %}
        {% include 'scripts.html' %}
    </body>
</html>

templates/footer.html
{% load static %}

<!-- Page Footer-->
<footer class="main-footer">
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="logo">
            <h6 class="text-white">Django Enthusiast Blog</h6>
            </div>
            <div class="contact-details">
            <p>Majengo - Sumbawanga</p>
            <p>Phone: (020) 123 456 789</p>
            <p>Email: <a href="innocent@djangoenthusiast.com">innocent@djangoenthusiastcom</a></p>
            <ul class="social-menu">
                <li class="list-inline-item">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li class="list-inline-item">
                    <a href="#"><i class="fa fa-github"></i></a>
                </li>
            </ul>
            </div>
        </div>
        <div class="col-md-6">
            <p class="lead">
                Meet Innocent Zenda
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam soluta iste odit quia veniam nemo consectetur dolorum molestiae? Consequuntur, quo.
            </p>
        </div>
        <div class="col-md-2 text-center">
            <img style="width:200px; height=200px;" src="{% static 'img/about-image.png' %} "class='rounded-circle' alt="">
        </div>
    </div>
</div>
<div class="copyrights">
    <div class="container">
    <div class="row">
        <div class="col-md-6">
        <p>&copy; 2019. All rights reserved. <a href="{% url 'blog:home' %}">Django Enthusiast</a></p>
        </div>
        <div class="col-md-6 text-right">
        <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
        </p>
        </div>
    </div>
    </div>
</div>
</footer>

templates/header.html
{% load static %}

<header class="header">
    <!-- Main Navbar-->
    <nav class="navbar sticky-top navbar-expand-lg">
        <div class="search-area">
            <div class="search-area-inner d-flex align-items-center justify-content-center">
                <div class="close-btn"><i class="icon-close"></i></div>
                <div class="row d-flex justify-content-center">
                <div class="col-md-8">
                    <form action="{% url 'blog:search-results' %}" method="POST">
                        {% csrf_token %}
                    <div class="form-group">
                        <input type="search" name="q" id="search" placeholder="What are you looking for?">
                        <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                    </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
        <div class="container">
        <!-- Navbar Brand -->
        <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{% url 'blog:home' %}" class="navbar-brand">Django Enthusiast</a>
            <!-- <img class='logo-image' src="{% static 'img/logo.png' %}" alt=""> -->
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
        </div>
        <!-- Navbar Menu -->
        <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link
            {% if request.path == '/' %}
            active
            {% endif %} ">Home</a>
            </li>
            <li class="nav-item"><a href="{% url 'blog:post-list' %}" class="nav-link {% if request.path == '/blog/' %}
                active
                {% endif %} ">Blog</a>
            </li>


            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link ">Logout</a>
                </li>
                {% if request.user.is_staff %}
                <li class="nav-item">
                        <a href="{% url 'blog:post-create' %}" class="nav-link {% if request.path == '/post-create/' %}
                            active
                            {% endif %} ">
                            New Post
                        </a>
                    </li>
                {% endif %}
            {% else %}
                <li class="nav-item"><a href="{% url 'users:register' %}" class="nav-link {% if request.path == '/users/register/' %}
                    active
                    {% endif %} ">Register</a>
                </li>
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link {% if request.path == '/users/login/' %}
                    active
                    {% endif %} ">Login</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'contact' %}" class="nav-link ">Contact</a>
            </li>
            </ul>
            <div class="navbar-text">
                <a href="{% url 'blog:search-results' %}" class="search-btn">
                    <i class="icon-search-1"></i>
                </a>
            </div>
            <!-- <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul> -->
        </div>
        </div>
    </nav>
</header>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


  <body>

    <!-- Hero Section-->
    <section style="background: url({% static 'img/hero.jpg' %}); background-size: cover; background-position: center center" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <h1>Welcome to Django Enthusiast Blog</h1><a href="#" class="hero-link">Discover More</a>
          </div>
        </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>
      </div>
    </section>
    <!-- Intro Section-->
    <section class="intro">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h2 class="h3">Some great intro here</h2>
            <p class="text-big">Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.</p>
          </div>
        </div>
      </div>
    </section>
    <section class="featured-posts no-padding-top">
      <div class="container">
        <!-- Post-->

        {% for post in featured_posts %}
        <div class="row d-flex align-items-stretch">
            {% if forloop.counter == 2 or  forloop.counter == 4 %}
              <div class="image col-lg-5">
                <img src="{{ post.thumbnail.url }}" alt="...">
              </div>
            {% endif %}
          <div class="text col-lg-7">
            <div class="text-inner d-flex align-items-center">
              <div class="content">
                <header class="post-header">
                  <div class="category">
                  {% for cat in post.categories.all %}
                  <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                  {% endfor %}
                  </div>
                  <a href="{{ post.get_absolute_url }}">
                    <h2 class="h4">{{ post.title }}</h2>
                  </a>
                </header>
                <p>
                  {{ post.overview }}
                </p>
                <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>{{ post.author }}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                  <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                </footer>
              </div>
            </div>
          </div>

          {% if forloop.counter == 1 or forloop.counter == 3 %}
          <div class="image col-lg-5">
            <img src="{{ post.thumbnail.url }}" alt="...">
          </div>
          {% endif %}

        </div>
        {% endfor %}

      </div>
    </section>
    <!-- Divider Section-->
    <section style="background: url({% static 'img/divider-bg.jpg' %}); background-size: cover; background-position: center bottom" class="divider">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2><a href="#" class="hero-link">View More</a>
          </div>
        </div>
      </div>
    </section>
    <!-- Latest Posts -->
    <section class="latest-posts">
      <div class="container">
        <header>
          <h2>Latest from the blog</h2>
          <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </header>
        <div class="row">
        {% for post in object_list %}
        <div class="post col-md-4">
            <div class="post-thumbnail">
              <a href="{{ post.get_absolute_url }}">
                <img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid">
              </a>
            </div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <!-- <div class="date">{{ post.timestamp |date }}</div> -->
                <div class="category">
                    {% for cat in post.categories.all %}
                    <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                    {% endfor %}
                </div>
              </div><a href="{{ post.get_absolute_url }}">
                <h3 class="h4">{{ post.title }}</h3></a>
              <p class="text-muted">
                {{ post.overview }}
              </p>
              <footer class="post-footer d-flex align-items-center">
                  <a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar">
                      <img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid">
                    </div>
                    <div class="title">
                      <span>{{ post.author }}</span>
                    </div>
                  </a>
                  <!-- <div class="date">
                    <i class="icon-clock"></i>
                    {{ post.timestamp|timesince }} ago
                  </div> -->
                  <div class="comments meta-last">
                    <i class="icon-comment"></i>{{ post.comment_count }}
                  </div>
                </footer>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>

    </section>
    <!-- Newsletter Section-->
    <section class="newsletter no-padding-top">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Subscribe to Newsletter</h2>
            <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="col-md-8">
            <div class="form-holder">
              <form action="." method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <input type="email" name="email" id="email" placeholder="Type your email address">
                  <button type="submit" class="submit">Subscribe</button>
                </div>
              </form>
              {% if messages %}

                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
                {% endfor %}

              {% endif %}


            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Gallery Section-->
    <section class="gallery no-padding">

      <div class="row">
          {% for item in gallery_items %}
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item">
            <a href="{{ item.thumbnail.url }}" data-fancybox="gallery" class="image">
              <img src="{{ item.thumbnail.url }}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center">
                <div class="text-center p-3">
                  <h3>{{ item.title }}</h3>
                  <p>
                    {{ item.description }}
                  </p>
              </div>
              </div>
            </a>
          </div>
        </div>
      {% endfor %}
        <!-- <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-2.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-2.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-3.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-3.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-4.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-4.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div> -->
      </div>
    </section>


{% endblock content %}

templates/search_results.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in object_list %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="post.html"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      <!-- <div class="date meta-last">{{ post.timestamp |date}}</div> -->
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div><a href="{{ post.get_absolute_url }}">
                      <h3 class="h4">{{ post.title }}</h3></a>
                    <p class="text-muted">
                      {{ post.content }}
                    </p>
                    <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                        <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                        <div class="title"><span>{{ post.author }}</span></div></a>
                      <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                      <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                    </footer>
                  </div>
                </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <!-- {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                     <i class="fa fa-angle-left"></i>
                    </a>
                  </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                  <li class="page-item">
                    <a href="?page={{ num }}" class="page-link active">{{ num }}</a>
                  </li>
                  {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                      <li class="page-item">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                      </li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
            {% endif %} -->
          </div>
        </main>
        {% include 'aside.html' %}
      </div>
    </div>
{% endblock content %}